### ISSUE TITLE
Security patches: Thunderbird vs Fossamail

### ISSUE THREAD

**Issue by positr0nic** [MoonchildProductions/FossaMail#32]
I am a Thunderbird user currently, but I am looking to switch permanently mainly due to the 64-bit support and the compatibility that Fossamail has with Thunderbird profiles, so the transition is smooth.

However looking at Thunderbird 45.8.0 (and previous) changelogs vs Fossamail's changelogs, I cant see any mention of any security or CVE fixes while Thunderbird has many.

I am simply curious from a outsider looking in, and hope to get some answer other than to just look or audit the sourcecode type answer.

Looking at the commit messages nothing of the sort seems to happen, so is the sourcecode really that secure?

**Comment by wolfbeast** [comment]
Security patches are almost invariably patches that apply to the platform. All these are adopted by updating our platform code used in FossaMail (and as such you can find the relevant and applicable security patch mentions in the Pale Moon release notes).
The source code commits that make these changes are marked with "Move back-end branch pointer" in most cases, which is all that is needed to update FossaMail's platform code to a completely-patched version of the underlying platform it builds on. While it would be possible to copy the relevant release notes from the browser that apply to FossaMail, it's just a waste of time.

A second note it that most CVEs listed for thunderbird are not even applicable since most apply to the situation where JavaScript can be used -- this is not possible in e-mail and as such those would not even apply.

**Comment by positr0nic** [comment]
Excellent thank you for clearing that up, yes I do see many such commits pulling the backend,

Thank you again for making the process clear.
